# Site settings
title: The "Clemagotchi"
email: rich.clemagotchi@richwareham.com
description: "Building a Valentine's Day present"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM
  hard_wrap: false

